#ifndef __K_SPECIES_H__
#define __K_SPECIES_H__

enum Species {
    SPECIES_NONE,
    SPECIES_SAPPURR,
    SPECIES_CAMOFLINE,
    SPECIES_VAMPIROOT,
    SPECIES_PYRUFF,
    SPECIES_FLAREWOLF,
    SPECIES_LYCARSON,
    SPECIES_SQUOINK,
    SPECIES_WOGHASH,
    SPECIES_SOLUBOAR,
    SPECIES_EGLET,
    SPECIES_REAGLE,
    SPECIES_REAGALIA,
    SPECIES_MUKCHUK,
    SPECIES_DIRTSKRT,
    SPECIES_PARCHICK,
    SPECIES_GROUFFLE,
    SPECIES_PONDURR,
    SPECIES_THALAGOS,
    SPECIES_COLAMB,
    SPECIES_ROYGIBAA,
    SPECIES_MAX
};


#endif